/**
 * HealthAssessment – Take a photo of a plant or farm animal,
 * submit it to the backend AI endpoint, and display a structured
 * health report generated by Claude vision.
 */

import { useState } from 'react';
import { Leaf, AlertTriangle, CheckCircle, Clock, ChevronDown, ChevronUp, Info } from 'lucide-react';
import CameraCapture, { CapturedPhoto } from '../../components/common/CameraCapture';
import { useAuthStore } from '../../store/authStore';

// ─── Types ────────────────────────────────────────────────────────────────────

type HealthStatus = 'HEALTHY' | 'MILD_CONCERN' | 'MODERATE_CONCERN' | 'SEVERE_CONCERN';
type Urgency = 'NONE' | 'LOW' | 'MEDIUM' | 'HIGH' | 'IMMEDIATE';

interface AssessmentResult {
  healthStatus: HealthStatus;
  confidence: number;
  issues: string[];
  recommendations: string[];
  urgency: Urgency;
  disclaimer: string;
}

interface ApiResponse {
  success: boolean;
  assessment: AssessmentResult;
  subjectType: string;
  county: string | null;
  assessedAt: string;
}

// ─── Subject type options ─────────────────────────────────────────────────────

const SUBJECT_OPTIONS = [
  { value: 'TEA',          label: 'Tea plant' },
  { value: 'MAIZE',        label: 'Maize crop' },
  { value: 'COFFEE',       label: 'Coffee plant' },
  { value: 'BEANS',        label: 'Beans crop' },
  { value: 'BANANA',       label: 'Banana plant' },
  { value: 'SWEET_POTATO', label: 'Sweet potato' },
  { value: 'DAIRY_COW',    label: 'Dairy cow' },
  { value: 'GOAT',         label: 'Goat' },
  { value: 'CHICKEN',      label: 'Chicken / Poultry' },
  { value: 'PIG',          label: 'Pig' },
  { value: 'OTHER_CROP',   label: 'Other crop' },
  { value: 'OTHER_ANIMAL', label: 'Other animal' },
];

// ─── Status display helpers ───────────────────────────────────────────────────

const STATUS_CONFIG: Record<HealthStatus, { label: string; color: string; icon: React.ReactNode }> = {
  HEALTHY:          { label: 'Healthy', color: 'text-green-700 bg-green-50 border-green-200',     icon: <CheckCircle className="h-5 w-5" /> },
  MILD_CONCERN:     { label: 'Mild concern', color: 'text-yellow-700 bg-yellow-50 border-yellow-200',   icon: <Info className="h-5 w-5" /> },
  MODERATE_CONCERN: { label: 'Moderate concern', color: 'text-orange-700 bg-orange-50 border-orange-200', icon: <AlertTriangle className="h-5 w-5" /> },
  SEVERE_CONCERN:   { label: 'Severe concern', color: 'text-red-700 bg-red-50 border-red-200',     icon: <AlertTriangle className="h-5 w-5" /> },
};

const URGENCY_CONFIG: Record<Urgency, { label: string; dot: string }> = {
  NONE:      { label: 'No action needed', dot: 'bg-green-400' },
  LOW:       { label: 'Low urgency',       dot: 'bg-yellow-400' },
  MEDIUM:    { label: 'Act within a week', dot: 'bg-orange-400' },
  HIGH:      { label: 'Act this week',     dot: 'bg-orange-600' },
  IMMEDIATE: { label: 'Act within 24-48h', dot: 'bg-red-600 animate-pulse' },
};

// ─── Component ────────────────────────────────────────────────────────────────

interface HealthAssessmentProps {
  county?: string;
}

export default function HealthAssessment({ county }: HealthAssessmentProps) {
  const { token } = useAuthStore();
  const [photo, setPhoto] = useState<CapturedPhoto | null>(null);
  const [subjectType, setSubjectType] = useState('TEA');
  const [context, setContext] = useState('');
  const [assessing, setAssessing] = useState(false);
  const [result, setResult] = useState<ApiResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showDetails, setShowDetails] = useState(true);

  const API_URL = (import.meta as unknown as { env: { VITE_API_URL?: string } }).env.VITE_API_URL ?? '';

  const runAssessment = async () => {
    if (!photo || !token) return;
    setAssessing(true);
    setError(null);
    setResult(null);
    try {
      const res = await fetch(`${API_URL}/api/ai/health-assessment`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({
          imageBase64: photo.base64,
          imageMimeType: photo.mimeType,
          subjectType,
          county,
          additionalContext: context || undefined,
        }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({ error: `HTTP ${res.status}` }));
        throw new Error((err as { error?: string }).error ?? `HTTP ${res.status}`);
      }
      setResult(await res.json() as ApiResponse);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Assessment failed. Please try again.');
    } finally {
      setAssessing(false);
    }
  };

  const reset = () => {
    setPhoto(null);
    setResult(null);
    setError(null);
    setContext('');
  };

  return (
    <div className="space-y-4">
      <div className="card p-4">
        <h2 className="section-title mb-3 flex items-center gap-2">
          <Leaf className="h-4 w-4 text-primary-700" /> AI Health Assessment
        </h2>
        <p className="text-sm text-gray-500 mb-4">
          Photograph a crop or farm animal to get an AI-powered health assessment and recommendations.
        </p>

        {!result && (
          <div className="space-y-4">
            {/* Subject type */}
            <div>
              <label className="label text-xs">What are you photographing? *</label>
              <select
                className="input text-sm"
                value={subjectType}
                onChange={(e) => setSubjectType(e.target.value)}
              >
                {SUBJECT_OPTIONS.map((o) => (
                  <option key={o.value} value={o.value}>{o.label}</option>
                ))}
              </select>
            </div>

            {/* Camera */}
            {!photo ? (
              <CameraCapture
                label="Photograph subject"
                onCapture={(p) => setPhoto(p)}
                maxKb={700}
              />
            ) : (
              <div className="rounded-xl overflow-hidden border border-gray-200">
                <img src={photo.dataUrl} alt="Captured" className="w-full max-h-64 object-contain bg-black" />
                <div className="flex items-center justify-between p-2 bg-white border-t border-gray-200">
                  <span className="text-xs text-gray-500">
                    {photo.fileSizeKb} KB
                    {photo.gpsLat && ' · GPS tagged'}
                  </span>
                  <button onClick={() => setPhoto(null)} className="text-xs text-gray-400 hover:text-gray-600">
                    Retake
                  </button>
                </div>
              </div>
            )}

            {/* Optional context */}
            {photo && (
              <div>
                <label className="label text-xs">Additional context (optional)</label>
                <textarea
                  className="input text-sm resize-none"
                  rows={2}
                  placeholder="e.g. 'Leaves started yellowing 2 weeks ago, after heavy rain'"
                  value={context}
                  onChange={(e) => setContext(e.target.value)}
                  maxLength={500}
                />
              </div>
            )}

            {error && (
              <div className="flex items-start gap-2 rounded-lg bg-red-50 border border-red-200 p-3 text-sm text-red-700">
                <AlertTriangle className="h-4 w-4 mt-0.5 flex-shrink-0" />
                {error}
              </div>
            )}

            <button
              onClick={runAssessment}
              disabled={!photo || assessing}
              className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {assessing ? (
                <>
                  <span className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
                  Analysing with AI…
                </>
              ) : (
                <><Leaf className="h-4 w-4" /> Run Health Assessment</>
              )}
            </button>
          </div>
        )}

        {/* ─── Result card ─────────────────────────────────────────────── */}
        {result && (
          <div className="space-y-4">
            {/* Photo thumbnail */}
            {photo && (
              <img src={photo.dataUrl} alt="Assessed" className="w-full max-h-48 object-contain bg-black rounded-lg" />
            )}

            {/* Status banner */}
            {(() => {
              const cfg = STATUS_CONFIG[result.assessment.healthStatus];
              return (
                <div className={`flex items-center gap-3 rounded-lg border p-4 ${cfg.color}`}>
                  {cfg.icon}
                  <div>
                    <div className="font-semibold">{cfg.label}</div>
                    <div className="text-xs opacity-75">
                      Confidence: {result.assessment.confidence}%
                    </div>
                  </div>
                  <div className="ml-auto text-right">
                    {(() => {
                      const u = URGENCY_CONFIG[result.assessment.urgency];
                      return (
                        <span className="inline-flex items-center gap-1.5 text-xs">
                          <span className={`h-2 w-2 rounded-full ${u.dot}`} />
                          {u.label}
                        </span>
                      );
                    })()}
                  </div>
                </div>
              );
            })()}

            {/* Details toggle */}
            <button
              onClick={() => setShowDetails(d => !d)}
              className="flex items-center gap-1 text-sm text-primary-700 hover:underline"
            >
              {showDetails ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
              {showDetails ? 'Hide details' : 'Show details'}
            </button>

            {showDetails && (
              <div className="space-y-3">
                {result.assessment.issues.length > 0 && (
                  <div>
                    <h4 className="font-semibold text-sm text-gray-800 mb-1 flex items-center gap-1">
                      <AlertTriangle className="h-3.5 w-3.5 text-orange-500" /> Issues identified
                    </h4>
                    <ul className="space-y-1">
                      {result.assessment.issues.map((issue, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                          <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-orange-400 flex-shrink-0" />
                          {issue}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {result.assessment.recommendations.length > 0 && (
                  <div>
                    <h4 className="font-semibold text-sm text-gray-800 mb-1 flex items-center gap-1">
                      <CheckCircle className="h-3.5 w-3.5 text-green-500" /> Recommendations
                    </h4>
                    <ol className="space-y-1 list-decimal list-inside">
                      {result.assessment.recommendations.map((rec, i) => (
                        <li key={i} className="text-sm text-gray-700">{rec}</li>
                      ))}
                    </ol>
                  </div>
                )}

                <div className="rounded-lg bg-gray-50 border border-gray-200 p-3 flex items-start gap-2 text-xs text-gray-500">
                  <Info className="h-3.5 w-3.5 flex-shrink-0 mt-0.5" />
                  {result.assessment.disclaimer}
                </div>

                <div className="flex items-center gap-1 text-xs text-gray-400">
                  <Clock className="h-3 w-3" />
                  Assessed {new Date(result.assessedAt).toLocaleString()}
                </div>
              </div>
            )}

            <div className="flex gap-3">
              <button onClick={reset} className="btn-secondary flex-1">
                New Assessment
              </button>
              <button
                onClick={() => window.print()}
                className="btn-secondary"
              >
                Print
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
